#!/usr/bin/env bash
# Set up Nginx to include a custom HTTP header in its responses on web-01 and web-02 servers
# The custom HTTP header should be named X-Served-By
# The custom HTTP header's value should be the hostname of the server where Nginx operates
sudo apt-get update
sudo apt-get -y install nginx

# Set up the firewall to permit requests via port 80
sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html

# Update permissions to allow easier file creation within this directory
sudo chmod -R 755 /var/www

# Generate the index page
echo 'Hello World!' |sudo tee  /var/www/html/index.html

# Generate an error 404 page
echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html

# Implement code to set up a redirect for a single page(/redirect_me) and include a header that shows the hostname
string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.blog.ehoneahobed.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Implement code to set up a redirect for the error 404 page
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Reboot the web server post settings update
sudo service nginx restart
