#!/usr/bin/env bash
# Craft a script for installing and setting up HAProxy on the lb-01 server
# Configure HAProxy to redirect traffic towards the web-01 and web-02 servers
# Employ a round-robin algorithm for request distribution
# Ensure that HAProxy can be controlled through an init script
# Perform HAproxy installation and setup on the lb-01 server
sudo apt-get -y update
apt-get -y install haproxy

# Modify the configuration file
server_config=\
"
frontend  yonas-frontend
        bind *:80
        mode http
        default_backend yonas-backend
backend yonas-backend
        balance roundrobin
        server 63210-web-01 100.25.19.204:80 check
        server 63210-web-02 54.157.159.85:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable control over haproxy using an init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
